### ISSUE TITLE
IllegalStateExecption

### ISSUE THREAD

**Issue by PSRCode** [lttng/lttng-scope#69]
Not sure how I got that:

> Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: flow.firstVisibleCell must not be null
> 	at org.lttng.scope.views.events.EventTable.getVisibleRowIndices(EventTable.kt:147)
> 	at org.lttng.scope.views.events.EventTable.access$getVisibleRowIndices(EventTable.kt:40)
> 	at org.lttng.scope.views.events.EventTable$selectIndex$1.run(EventTable.kt:119)
> 	at com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
> 	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
> 	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
> 	at java.lang.Thread.run(Thread.java:748)
>

**Comment by alexmonthy** [comment]
Did you get that soon after opening or closing a project? I see where there could be a race condition on view creation or teardown. I could push a fix to avoid that particular NPE, but would like to be sure it is not due to something else.

**Comment by alexmonthy** [comment]
Let's go with this fix, let me know if it happens again.
